info:
  contact: {}
  license: {}
paths:
  /api/articles/{id}:
    get:
      parameters:
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":""}]'
          schema:
            type: string
      summary: Get article
  /api/articles/list:
    get:
      parameters:
      - {}
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":[{"id":1,"title":"abc"}]}'
          schema:
            type: string
      summary: Get Article List
  /api/user/add:
    post:
      parameters:
      - {}
      - {}
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":1}'
          schema:
            type: string
      summary: Add User
  /api/user/delete:
    post:
      parameters:
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200, "msg": "操作成功", "data":""}'
          schema:
            type: string
      summary: Delete User
  /api/user/list:
    get:
      parameters:
      - {}
      - {}
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"id":1,"name":"Mantis", "email":"tangchunlinit@gmail.com"}]'
          schema:
            type: string
      summary: Get User List
swagger: "2.0"
